import React,{useEffect,useMemo,useState} from "react";
import {Routes,Route,Link,useLocation,useNavigate,useSearchParams} from "react-router-dom";
import {AnimatePresence,motion} from "framer-motion";
import {Menu as MenuIcon,X,ShoppingBag,Search,MapPin,Phone,Clock,Instagram,Facebook,ChevronRight,Star,ArrowRight,UtensilsCrossed,CalendarDays,Heart,Plus,Minus,UserRound,LogIn,UserPlus,Send,CheckCircle2,Flame,Leaf,Sparkles,ChefHat} from "lucide-react";
import {dishes,categories,gallery,categoryStories} from "./data";

const money=n=>`PKR ${n.toLocaleString()}`;
function Layout({children,cartCount}) {
 const [open,setOpen]=useState(false); const loc=useLocation();
 const links=[["Home","/"],["Our Menu","/menu"],["Food Categories","/categories"],["Our Story","/about"],["Our Gallery","/gallery"],["Offers","/offers"],["Reviews","/reviews"],["Get In Touch","/contact"]];
 return <div className="site">
  <div className="topbar"><span><MapPin size={14}/> Quetta, Balochistan</span><span><Clock size={14}/> Open daily 12 PM – 12 AM</span><span className="top-right"><Phone size={14}/> +92 300 0000000</span></div>
  <header className="nav">
   <Link to="/" className="brand"><span className="brand-mark"><Flame size={21}/></span><span>MUBARAK<small>FOOD & RESTAURANT</small></span></Link>
   <button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button>
   <nav className={open?"open":""}>{links.map(([n,p])=><Link key={p} className={loc.pathname===p?"active":""} onClick={()=>setOpen(false)} to={p}>{n}</Link>)}<Link to="/login" className="nav-login"><UserRound size={16}/> Account</Link><Link to="/order" className="nav-order"><ShoppingBag size={17}/> Order {cartCount>0&&<b>{cartCount}</b>}</Link></nav>
  </header>
  <main>{children}</main>
  <footer className="footer"><div className="footer-main"><div><Link to="/" className="brand light"><span className="brand-mark"><Flame size={21}/></span><span>MUBARAK<small>FOOD & RESTAURANT</small></span></Link><p>Warm plates, bold flavours and a table made for everyone.</p><div className="social"><Instagram/><Facebook/></div></div><div><h4>Explore</h4><Link to="/menu">Our Menu</Link><Link to="/offers">Offers</Link><Link to="/gallery">Gallery</Link></div><div><h4>Visit Us</h4><p><MapPin/> Jinnah Road, Quetta</p><p><Phone/> +92 300 0000000</p><p><Clock/> 12 PM – 12 AM</p></div><div><h4>Stay in the loop</h4><p>Get occasional updates and special offers.</p><div className="newsletter"><input placeholder="Your email"/><button><ArrowRight/></button></div></div></div><div className="footer-bottom"><span>© 2026 Mubarak Food & Restaurant</span><span>Placeholder contact details for demo</span></div></footer>
 </div>
}
function Hero(){
 return <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={16}/> AUTHENTIC FLAVOUR · QUETTA</span><h1>Taste that brings <em>everyone</em> together.</h1><p>From sizzling BBQ to comforting Pakistani classics, every plate is prepared with care and served with warmth.</p><div className="actions"><Link className="btn primary" to="/menu">Explore Menu <ArrowRight size={18}/></Link><Link className="btn ghost" to="/reservation"><CalendarDays size={18}/> Reserve a Table</Link></div><div className="hero-proof"><div className="avatars"><span>MK</span><span>SA</span><span>AH</span></div><div><div className="stars">★★★★★</div><small>Loved by local foodies</small></div></div></div><div className="hero-art"><img src="/images/food-1.jpg"/><div className="float-card"><ChefHat/><span>Chef's pick<strong>BBQ Platter</strong></span></div><div className="ring3d r1"></div><div className="ring3d r2"></div></div></section>
}
function Home({add}){return <><Hero/><section className="section"><div className="section-head"><div><span className="eyebrow">FROM OUR KITCHEN</span><h2>Popular on the table</h2></div><Link to="/menu" className="text-link">View full menu <ArrowRight size={17}/></Link></div><div className="dish-grid">{dishes.slice(0,4).map(d=><DishCard key={d.id} d={d} add={add}/>)}</div></section><section className="story-strip"><div className="story-img"><img src="/images/food-9.jpg"/></div><div className="story-copy"><span className="eyebrow">THE MUBARAK TABLE</span><h2>Good food is better when it is shared.</h2><p>We bring familiar flavours, generous portions and a welcoming atmosphere together for memorable meals in Quetta.</p><Link to="/about" className="btn dark">Our Story <ArrowRight size={18}/></Link></div></section><section className="features"><Feature icon={<Leaf/>} title="Fresh ingredients" text="Prepared daily with carefully selected ingredients."/><Feature icon={<UtensilsCrossed/>} title="Made to order" text="Hot, generous and finished when you order."/><Feature icon={<Heart/>} title="Made for families" text="Comfortable dining for friends and family."/><Feature icon={<Flame/>} title="Flame grilled" text="Signature BBQ cooked over a real flame." /></section><section className="offer-banner"><div><span className="eyebrow">WEEKEND SPECIAL</span><h2>Family Feast · PKR 2,990</h2><p>BBQ platter, karahi, rice, naan and drinks for the table.</p><Link to="/offers" className="btn lightbtn">See today's offers</Link></div><div className="offer-food"><img src="/images/food-8.jpg"/></div></section><Reviews/></>}
function Feature({icon,title,text}){return <div className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function DishCard({d,add}){return <motion.article whileHover={{y:-6}} className="dish-card"><div className="dish-img"><img src={d.img}/><span>{d.cat}</span><button aria-label="Add to favourites"><Heart size={17}/></button></div><div className="dish-info"><div><h3>{d.name}</h3><p>{d.desc}</p></div><strong>{money(d.price)}</strong></div><button className="add-btn" onClick={()=>add(d)}><Plus size={17}/> Add to order</button></motion.article>}
function Reviews(){return <section className="section reviews"><div className="section-head"><div><span className="eyebrow">GUEST NOTES</span><h2>Made memorable.</h2></div></div><div className="review-grid">{["“The BBQ platter was beautifully smoky and generous. We left happy.”","“Warm service, great portions and the kind of karahi you want with fresh naan.”","“A lovely place for family dinner. Everything arrived hot and full of flavour.”"].map((t,i)=><div className="review" key={t}><div className="stars">★★★★★</div><p>{t}</p><b>{["Ayesha K.","Hamza R.","Sana M."][i]}</b><small>Quetta · Verified visit</small></div>)}</div></section>}
function MenuPage({add}){const [params]=useSearchParams(); const initialCat=params.get("category")||"All"; const [cat,setCat]=useState(initialCat),[q,setQ]=useState(""); const list=useMemo(()=>dishes.filter(d=>(cat==="All"||d.cat===cat)&&(d.name+d.desc).toLowerCase().includes(q.toLowerCase())),[cat,q]);return <PageHead eyebrow="OUR MENU" title="A story on every plate" text="Every dish has a place at the table. Explore our complete menu, choose a craving, and follow it from the kitchen to your order."><div className="menu-story"><div><span className="eyebrow">THE KITCHEN JOURNEY</span><h2>Start with the flavour you came for.</h2><p>Our menu moves from live-fire BBQ to homestyle Pakistani favourites, quick wok dishes, burgers, rice and a sweet finish. Every card below has its own food image so you can see what you are choosing.</p></div><img src="/images/food-9.jpg"/></div><div className="menu-toolbar"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search dishes..."/></div><div className="chips">{categories.map(c=><button className={cat===c?"selected":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><div className="menu-grid-intro"><span>{list.length} dishes shown</span><span>Freshly presented · PKR pricing</span></div><div className="dish-grid menu-grid">{list.map(d=><DishCard key={d.id} d={d} add={add}/>)}</div></PageHead>}

function CategoriesPage(){return <PageHead eyebrow="FOOD CATEGORIES" title="Choose the chapter of your meal" text="Instead of one long list, explore Mubarak through the flavours that define the table. Each category has its own story and its own visual identity."><div className="category-story-grid">{categoryStories.map((c,i)=><motion.article whileHover={{y:-7}} className="category-story" key={c.name}><div className="category-story-img"><img src={c.image}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="category-story-copy"><span className="eyebrow">{c.name}</span><h2>{c.title}</h2><p>{c.text}</p><Link className="text-link" to={`/menu?category=${encodeURIComponent(c.name)}`}>Explore {c.name} <ArrowRight size={16}/></Link></div></motion.article>)}</div></PageHead>}
function PageHead({eyebrow,title,text,children}){return <div className="page"><div className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{children}</div>}
function About(){return <PageHead eyebrow="OUR STORY" title="A table with a little more warmth" text="Mubarak Food & Restaurant is a modern home for the flavours Quetta loves."><section className="about-layout"><div className="about-photo"><img src="/images/food-10.jpg"/><div className="stamp">MUBARAK<br/><small>EST. QUETTA</small></div></div><div className="about-copy"><span className="eyebrow">SINCE THE FIRST PLATE</span><h2>Simple food. Honest hospitality.</h2><p>Our idea is straightforward: serve food that feels familiar, cooked with attention and shared in a room that feels welcoming.</p><p>From the first sizzle of BBQ to the last spoon of dessert, we care about flavour, freshness and the little details that turn dinner into a memory.</p><div className="stats"><div><b>4+</b><span>Years of craft</span></div><div><b>50+</b><span>Menu favourites</span></div><div><b>10k+</b><span>Happy plates</span></div></div></div></section><section className="values"><Feature icon={<Leaf/>} title="Fresh first" text="Ingredients selected for flavour and consistency."/><Feature icon={<ChefHat/>} title="Crafted by chefs" text="Classic recipes finished with a modern touch."/><Feature icon={<Heart/>} title="Hospitality" text="A relaxed table for families, friends and guests." /></section></PageHead>}
function Gallery(){const [filter,setFilter]=useState("All");return <PageHead eyebrow="THE GALLERY" title="A feast for the eyes" text="A glimpse into our dishes, dining room and the moments around the table."><div className="gallery-filter">{["All","Food","Restaurant","BBQ","Events"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="gallery-grid">{gallery.map((g,i)=><motion.div whileHover={{scale:1.02}} className={`gallery-item gi${i%5}`} key={g}><img src={g}/><span>{i%3===0?"BBQ":i%3===1?"Mubarak table":"Fresh from the kitchen"}</span></motion.div>)}</div></PageHead>}
function Offers({add}){const offers=[dishes[7],dishes[0],dishes[4]];return <PageHead eyebrow="GOOD DEALS" title="More flavour, more to share" text="Seasonal specials and table-friendly bundles."><div className="big-offer"><div><span className="eyebrow">THIS WEEKEND</span><h2>Family Feast</h2><p>BBQ platter + chicken karahi + rice + naan + 4 drinks.</p><div className="price-row"><s>PKR 3,650</s><b>PKR 2,990</b><span>-18%</span></div><button className="btn primary" onClick={()=>add(offers[0])}>Add feast <ShoppingBag size={17}/></button></div><img src="/images/food-8.jpg"/></div><div className="offer-grid">{offers.map((d,i)=><div className="offer-card" key={d.id}><img src={d.img}/><div><span>LIMITED</span><h3>{i===0?"Family Feast":i===1?"BBQ Night":"Lunch Table"}</h3><p>{d.desc}</p><b>{money(d.price)}</b><button onClick={()=>add(d)}>Add to order <Plus size={15}/></button></div></div>)}</div></PageHead>}
function Order({cart,add,remove,clear}){const total=cart.reduce((s,x)=>s+x.price*x.qty,0);return <PageHead eyebrow="ORDER ONLINE" title="Bring Mubarak to your table" text="Build your order and review it before checkout. This demo does not process payments."><div className="order-layout"><div><div className="order-list">{dishes.slice(0,6).map(d=><div className="order-item" key={d.id}><img src={d.img}/><div><span>{d.cat}</span><h3>{d.name}</h3><p>{money(d.price)}</p></div><button onClick={()=>add(d)}><Plus/></button></div>)}</div></div><aside className="cart"><div className="cart-title"><h2>Your order</h2><span>{cart.reduce((s,x)=>s+x.qty,0)} items</span></div>{cart.length===0?<div className="empty"><ShoppingBag/><p>Your basket is waiting for something delicious.</p></div>:cart.map(x=><div className="cart-row" key={x.id}><div><b>{x.name}</b><small>{money(x.price)} × {x.qty}</small></div><div className="qty"><button onClick={()=>remove(x)}><Minus/></button><span>{x.qty}</span><button onClick={()=>add(x)}><Plus/></button></div></div>)}<div className="totals"><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Delivery</span><b>{cart.length?money(150):money(0)}</b></div><div className="grand"><span>Total</span><b>{money(total+(cart.length?150:0))}</b></div></div><Link className="btn primary full" to={cart.length?"/checkout":"/menu"}>{cart.length?"Continue to checkout":"Browse menu"} <ArrowRight/></Link></aside></div></PageHead>}
function Contact(){return <PageHead eyebrow="SAY HELLO" title="Come hungry. Leave happy." text="We are here for reservations, questions, feedback and everything in between."><div className="contact-grid"><div className="contact-cards"><Info icon={<MapPin/>} title="Visit us" text="Jinnah Road, Quetta, Balochistan, Pakistan"/><Info icon={<Phone/>} title="Call / WhatsApp" text="+92 300 0000000"/><Info icon={<Clock/>} title="Opening hours" text="Every day · 12 PM – 12 AM"/><Info icon={<Send/>} title="Email" text="info@mubarakrestaurant.example"/></div><form className="contact-form" onSubmit={e=>e.preventDefault()}><h2>Send a message</h2><div className="two"><input placeholder="Your name"/><input placeholder="Phone number"/></div><input placeholder="Email address"/><textarea rows="6" placeholder="How can we help?"></textarea><button className="btn primary">Send message <ArrowRight/></button></form></div><div className="map"><div className="map-pin"><MapPin/><b>Mubarak Food & Restaurant</b><span>Quetta · placeholder location</span></div><div className="road rA"></div><div className="road rB"></div><div className="road rC"></div></div></PageHead>}
function Info({icon,title,text}){return <div className="info"><div>{icon}</div><section><h3>{title}</h3><p>{text}</p></section></div>}
function Reservation(){return <PageHead eyebrow="YOUR TABLE" title="Reserve a table" text="Choose a time and we’ll keep your table ready."><div className="reservation"><img src="/images/food-11.jpg"/><form onSubmit={e=>e.preventDefault()}><h2>Let's make room for you.</h2><div className="two"><label>Date<input type="date"/></label><label>Time<select><option>7:00 PM</option><option>8:00 PM</option><option>9:00 PM</option></select></label></div><label>Guests<select><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>6 guests</option></select></label><label>Name<input placeholder="Your full name"/></label><label>Phone<input placeholder="+92 ..."/></label><label>Special request<textarea rows="3" placeholder="Birthday, family table, allergies..."></textarea></label><button className="btn primary">Confirm reservation <CalendarDays size={18}/></button><small>Demo only — no real reservation will be submitted.</small></form></div></PageHead>}
function ReviewsPage(){return <PageHead eyebrow="GUEST NOTES" title="What people say" text="A few words from our growing table of guests."><div className="rating-head"><div><b>4.8</b><div className="stars">★★★★★</div><span>Based on demo reviews</span></div><div className="bars">{[["5 stars","88%"],["4 stars","8%"],["3 stars","3%"],["2 stars","1%"]].map(x=><div key={x[0]}><span>{x[0]}</span><i><b style={{width:x[1]}}></b></i><small>{x[1]}</small></div>)}</div></div><Reviews/><div className="review-form"><h2>Share your experience</h2><div className="stars big">★★★★★</div><textarea placeholder="Tell us about your visit..."></textarea><button className="btn primary">Submit review</button></div></PageHead>}
function Auth({mode}){const nav=useNavigate(),[signup,setSignup]=useState(mode==="signup"); const submit=e=>{e.preventDefault();localStorage.setItem("mubarak-demo-user",e.currentTarget.email.value);nav("/");};return <div className="auth"><div className="auth-visual"><img src="/images/food-12.jpg"/><div><span className="eyebrow">WELCOME TO THE TABLE</span><h1>Good food starts with a warm welcome.</h1><p>Create a demo account to save your favourite dishes and make ordering feel effortless.</p></div></div><div className="auth-card"><Link to="/" className="brand"><span className="brand-mark"><Flame size={21}/></span><span>MUBARAK<small>FOOD & RESTAURANT</small></span></Link><h2>{signup?"Create your account":"Welcome back"}</h2><p>{signup?"Join the table in a few seconds.":"Sign in to continue your demo experience."}</p><form onSubmit={submit}>{signup&&<input name="name" required placeholder="Full name"/>}<input name="email" type="email" required placeholder="Email address"/><input name="password" type="password" required placeholder="Password"/><button className="btn primary full">{signup?<><UserPlus/> Create account</>:<><LogIn/> Sign in</>}</button></form><button className="switch" onClick={()=>setSignup(!signup)}>{signup?"Already have an account? Sign in":"New here? Create an account"}</button><small className="demo-note">Demo authentication only. No backend or real account is created.</small></div></div>}
function Checkout(){return <PageHead eyebrow="CHECKOUT" title="Almost on the way" text="This is a front-end demo checkout — no payment will be charged."><div className="checkout"><form onSubmit={e=>e.preventDefault()}><h2>Delivery details</h2><input placeholder="Full name"/><input placeholder="Phone number"/><input placeholder="Delivery address"/><textarea rows="4" placeholder="Delivery notes"></textarea><button className="btn primary">Place demo order <CheckCircle2/></button></form><div className="checkout-art"><img src="/images/food-13.jpg"/><div><span className="eyebrow">DEMO CHECKOUT</span><h2>Fresh from our kitchen.</h2><p>Payment integration can be connected later.</p></div></div></div></PageHead>}
function App(){const [cart,setCart]=useState([]); const add=d=>setCart(c=>{const f=c.find(x=>x.id===d.id);return f?c.map(x=>x.id===d.id?{...x,qty:x.qty+1}:x):[...c,{...d,qty:1}]}); const remove=d=>setCart(c=>c.flatMap(x=>x.id===d.id?(x.qty>1?[{...x,qty:x.qty-1}]:[]):[x])); const count=cart.reduce((s,x)=>s+x.qty,0); return <Layout cartCount={count}><AnimatePresence mode="wait"><Routes><Route path="/" element={<Home add={add}/>}/><Route path="/menu" element={<MenuPage add={add}/>}/><Route path="/categories" element={<CategoriesPage/>}/><Route path="/about" element={<About/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/offers" element={<Offers add={add}/>}/><Route path="/order" element={<Order cart={cart} add={add} remove={remove}/>}/><Route path="/contact" element={<Contact/>}/><Route path="/reservation" element={<Reservation/>}/><Route path="/reviews" element={<ReviewsPage/>}/><Route path="/login" element={<Auth mode="login"/>}/><Route path="/signup" element={<Auth mode="signup"/>}/><Route path="/checkout" element={<Checkout/>}/></Routes></AnimatePresence></Layout> }
export default App;
